### PR TITLE
Last chance from restoring multilayers direct and MCMC computations

### PR DESCRIPTION
**Pull request by fabien-ors**
This PR should propose a version of Molonaviz that is able to launch direct model and MCMC inversion on multi-layers parameters. The database is kept consistent with results shown in the plots. BestParameters table is no more used. Indeed, Parameters table is enough to store the best parameters identified by the inversion (the direct model is computed after the inversion using these best parameters).

This PR should fix the following issues: #12 and #16

### CODE REVIEW

**Comment by fabien-ors** [comment]
Wait few minutes before merging plz.
i have one remaining commit to do

**Comment by flipoyo** [comment]
shall I proceed or wait a bit ?

**Comment by fabien-ors** [comment]
wait a bit

**Comment by fabien-ors** [comment]
Now you can !

**Pull request merged**
