### PR TITLE
GitHub Actions: Re-run demoPyheatmy.ipynb

### LINKED ISSUE #85: pyheatmy: Potential NaN values in core.py
There seems to be a stability issue with pyheatmy/core.py around line 1022 in `np.random.choice(ncr, p=pcr[l])`, `pcr[l]` sometimes contains NaNs that make `np.random.choice` raise `ValueError: probabilities contain NaN`.

This issue has been noticed when running `demoPyheatmy.ipynb` under the GitHub Actions workflow (c.f. #80).

An additional check should be added somewhere in the function to ensure that NaN value are properly handled: should we replace them with 0? should we skip the corresponding for loop iteration?

### LINKED ISSUE #91: add demoPyheat.ipynb to CI
To test the NaN generation in core.py.
I cannot reproduce the bug with py3.11.4
related to issue #85

### PR DESCRIPTION
**Pull request by pierre-guillou**
This PR re-adds the `demoPyheatmy.ipynb` Jupyter notebook to be executed through GitHub Actions.

I don't know why (yet) but we still need to add a check to pyheatmy/pyheatmy/core.py to avoid a `ValueError` in `np.random.choice`. The test doesn't seem to be triggered but without it, the CI fails…

Fix #85.
Fix #91.

Pierre

### CODE REVIEW

**Review by flipoyo — APPROVED** [review]
Very awkward especially that this piece of code isn't call bien demoPyheatmy.ipynb.  The method def compute_dream_mcmc_without_sigma2 where your control is located isn't call by this notebook but by DREAM_V1, which is not bugged. I don't get it

**Comment by flipoyo** [comment]
The CI failed on your check. I think a controll should be set up in def compute_mcmc core.py, to check the number of chains line 1299. Something may be wrongly defined beforehand

**Comment by pierre-guillou** [comment]
The method `compute_dream_mcmc_without_sigma2` is called by `demoPyheatmy.ipynb` through the `checker.py` decorator (see for instance error backtrace at https://github.com/flipoyo/MOLONARI1D/actions/runs/11441152805/job/31829134736?pr=94).
The check I've just added has triggered the error.
Now what I don't understand yet is why it did work without errors in my fork but not here…

**Comment by flipoyo** [comment]
I found the bug, see Fix#100

**Pull request merged**
