### PR TITLE
GitHub Actions: Run Jupyter Notebooks

### LINKED ISSUE #76: improve CI of pyheatmy
Is it possible to add to the pyheatmy CI the fact that a jupyter note book is properly executed until the end ?

If yes, in pyheatmy, verify that 
+ demoPyheatmy.ipynb runs
+ pyheatmy/DREAMS_V1.ipynb and pyheatmy/DREAMS_V3.ipynb run
+ research/synthetic_case_generator/demo_genData.ipynb runs

### PR DESCRIPTION
**Pull request by pierre-guillou**
This PR extends the GitHub Actions workflow to also run 4 `pyheatmy` Jupyter Notebooks. These are run until completion, no testing on the cell values is performed (yet).

Two issues were noticed when running these notebooks:
- [ ] pyheatmy/pyheatmy/DREAM_v3.ipynb uses an undefined variable (`n_sous_ech_temp` at line 309),
- [ ] pyheatmy/pyheatmy/DREAM_v1.ipynb tries to save into a non-existing`images` directory: `plt.savefig(f"../images/threshold_{int(threshold*100)}.png")`. Although the workflow creates this directory, it would be better if it was handled by the notebook itself.

Also, a `__pycache__` directory and its content has been removed.

Fix #76.

Pierre

### CODE REVIEW

**Review by flipoyo — CHANGES_REQUESTED** [review]
Merci, le notebook DREAM_V3 est buggé, peut-on l'enlever ?
Pour DREAM_V1, peux-tu commenter la ligne de commande pour l'impression.

Pour ma gouverne, si les notebooks sont modifiés, le test prendra bien en compte le notebook modifié ?

**Comment by pierre-guillou** [comment]
Si tu modifies un des  3 notebooks testés, il faut que les modifications soit pushées vers GitHub dans une branche en aval de cette PR, i.e. contenant les commits de celle-ci (une fois mergée).

**Comment by pierre-guillou** [comment]
There seems to be a stability issue with `demoPyheatmy.ipynb`: in `pyheatmy/core.py`, around line 1022 in `np.random.choice(ncr, p=pcr[l])`, `pcr[l]` sometimes contains NaNs that are not accepted by Numpy.

**Comment by flipoyo** [comment]
Can you please create a new issue for that problem and remove demoPyheatmy.ipynb from the CI.

My other question is why all the pyheatmy CI test are cancelled after 6m ?

**Comment by pierre-guillou** [comment]
If one job fails, every other job is cancelled.

**Comment by flipoyo** [comment]
OK if we remove DemoPyheatmy, the others should work ?

**Comment by pierre-guillou** [comment]
So far everything seems good.

**Comment by flipoyo** [comment]
it was sufficient to remove demoPyheatmy ?

**Review by flipoyo — APPROVED** [review]

**Comment by pierre-guillou** [comment]
I needed to extend the timeout to run individual notebook cells from 300s to 600s to make everything pass in addition to removing `demoPyheatmy.ipynb`.

**Pull request merged**
